language: python
env:
  global:
    - secure: "K7ftkaKYCmLWOln+GHnQOu1Z1VafSyn+0O5fGt+GunjaDcwbK4A/Z3CjO1bzVgeraonB3e5zB6K9e9J1UQDs16J1rl2XOD3wpvrIICZw3riZLH/94/wWZsAFmIzqLwsj7qnp8wzasIEgBdlFyE7mJC/y+p25diUBPhx7xtG4e/g="
    - secure: "jTDcWJVqvkncOJGyqSdMQ4tmHtp4lQcAGMbfHOZXtUzr8TCCF+h/z6X0KNcgwgXsRN0af2vY8Cm44jnrADQ4lKYKrIfyqvQrdJ2X2sHCv3RwMxyC9mCvDU5X7JQ7/1zCra0bXqOusSpGGU302O5Aj3V4T0b6F0IEU3Sm+wfzIAU="
    - DEPLOY_PATH=/var/www/doc/
python:
  - 2.7
install:
  - pip install -r requirements.txt
script:
  - rm -rf build/ tmp/
  - sphinx-build -aE -nW -Dlanguage='en' -b html -d tmp source/ build/en
  - sphinx-build -aE -nW -Dlanguage='fr' -b html -d tmp source/ build/fr
  - sphinx-build -aE -nW -Dlanguage='es' -b html -d tmp source/ build/es
  - sphinx-build -aE -nW -Dlanguage='de' -b html -d tmp source/ build/de
  - sphinx-build -aE -nW -Dlanguage='nl' -b html -d tmp source/ build/nl
after_success:
  - openssl aes-256-cbc -K $encrypted_9f7cba75ae55_key -iv $encrypted_9f7cba75ae55_iv -in .travis.deploy.enc -out .travis.deploy -d
  - chmod 600 .travis.deploy
  - eval "$(ssh-agent -s)"
  - ssh-add .travis.deploy
  - 'test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && rsync -e "ssh -o StrictHostKeyChecking=no" -az --force --delete build/ "$DEPLOY_USER"@"$DEPLOY_IP":"$DEPLOY_PATH" 2>/dev/null'
sudo: false
notifications:
  slack:
    secure: APEJ/vt/8HAE8OWGR3DfL+XBQl4/Q35nN216+cFmuSHKuniV+XwLkvM3sEIC5OPABsxg/37oqoYr0a39PHyGQvBZ5ie9s9LpUsXUd76QgDZzR9BYxid9Atg2KXGqn2vrxJ8ZyKkQyd6VivJ8TtX8hlRsTZsx7fmbDqr9omzDldg=
